testing: create matchMedia object in window for jest
Jest shows an error when running tests:
`TypeError: window.matchMedia is not a function`

the above error is caused by the fact that jest is trying to access a
matchMedia object in the window object that doesn't exist.

Changes to be committed:
	modified:   apps/toctive-blog/frontend/jest.config.ts
	modified:   apps/toctive-blog/frontend/pages/_app.tsx
	new file:   apps/toctive-blog/frontend/specs/jest.setup.js